 export const TRAVEL_INIT_INFO = 'TRAVEL_INIT_INFO';
 export const TRAVEL_CONTENT_INFO = 'TRAVEL_CONTENT_INFO';
 export const TRAVEL_BOTTOM_INFO = 'TRAVEL_BOTTOM_INFO';
 export const GET_INFOLIST='GET_INFOLIST';
export const REST_PAGECOUNT='REST_PAGECOUNT';
export const UPDATE_LOADING='UPDATE_LOADING';
export const UPDATE_REFRESH='UPDATE_REFRESH';
// export const GET_INFOLIST='GET_INFOLIST';
// export const REST_PAGECOUNT='REST_PAGECOUNT';
// export const UPDATE_LOADING='UPDATE_LOADING';
// export const UPDATE_REFRESH='UPDATE_REFRESH';
// export const FARMER_DETAIL='FARMER_DETAIL';

//3.1使用store进行数据的传递管理